server:
        {
listen 127.0.0.1:8080
server_name example.com
root /var/www/html
404 /errors/404.html
401 /errors/401.html
409 /errors/409.html
405 /errors/405.html
autoindex on
index index.html
upload on
upload_location /var/www/uploads
max_payload_size 10485760
location /api
            {
root /var/www/api
autoindex off
}
location /api2
{
root /var/www/api2
autoindex off
}
}
server:
{
listen 127.0.0.1:8080
server_name example.com
root /var/www/html
404 /errors/404.html
401 /errors/401.html
409 /errors/409.html
405 /errors/405.html
autoindex on
index index.html
upload on
upload_location /var/www/uploads
max_payload_size 10485760
location /api
{
root /var/www/api
autoindex off
}
location /api2
{
root /var/www/api2
autoindex off
}
      }
