server:
{
      listen 0.0.0.0:100
      server_name example.com
      root ./root/
      404 /errors/404.html
      409 /errors/409.html
      405 /errors/405.html
      autoindex on
      index index.html
      upload on
      upload_location ./root/uploads
      max_payload_size 10485760
      location /tests
      {
            root ./root/tests
            autoindex on
      }
      location /tests/autoindex-on
      {
            root ./root/tests/autoindex-on
            autoindex on
      }
      location /tests/autoindex-off
      {
            root ./root/tests/autoindex-off
            autoindex off
      }
      location /tests/redirect-302
      {
            return 302 /tests/redirect-302/index.html
      }
      location /tests/upload-allowed
      {
            root ./root/tests/upload-allowed
            upload on
            upload_location ./root/uploads
      }
      location /tests/upload-denied
      {
            root ./root/tests/upload-denied
            upload off
      }
      location /tests/permission-403
      {
            root ./root/tests/permission-403
            autoindex off
      }
      location /tests/errors
      {
            root ./root/tests/errors
            autoindex on
      }
      location /api/hihi
      {
            return 302 /api2
      }
      location /api2
      {
            return 302 /api/hihi
      }
      location /cgi
      {
            cgi_extension .py /opt/pyenv/shims/python
      }
      location /hehe
      {
            return 302 https://chatgpt.com
            cgi_extension .py /usr/bin/cgi
      }
}
