server:
        {
listen 127.0.0.1:8080
server_name example.com
root ./root/
404 /errors/404.html
401 /errors/401.html
409 /errors/409.html
405 /errors/405.html
autoindex on
index index.html
upload on
upload_location ./root/uploads
max_payload_size 10485760
location /api
            {
root ./root/api
}
location /api2
{
root ./root/api2
autoindex off
}
}
server:
{
listen 127.0.0.2:8080
server_name example.com
root ./root/
401 /errors/401.html
404 /errors/404.html
405 /errors/405.html
409 /errors/409.html
autoindex on
index index.html
upload on
upload_location ./root/uploads
max_payload_size 10485760
location /api
{
root ./root/api
autoindex off
}
location /api2
{
root ./root/api2
autoindex off
}
      }
server:
{
listen 127.0.0.1:8080
server_name example.com
root ./root/
401 /errors/401.html
404 /errors/404.html
405 /errors/405.html
409 /errors/409.html
autoindex on
index index.html
upload on
upload_location ./root/uploads
max_payload_size 10485760
location /api
{
root ./root/api
autoindex off
}
location /api2
{
root ./root/api2
autoindex off
}
      }
